import { Project } from "types/types";

export const projectsList: Project[] = [
  {
    id: 0,
    imageURL: "projects/brodilkaviborg/logo.png",
    name: "projects/questViborg",
    content_locales: "brodilkaviborg",
    tag_count: 1,
  },
  {
    id: 1,
    imageURL: "projects/backtotheroots/logo.png",
    name: "projects/backToTheRootsLanding",
    content_locales: "backtotheroots",
    tag_count: 1,
  },
  {
    id: 2,
    imageURL: "projects/mymoscow/logo.png",
    name: "projects/myMoscow",
    content_locales: "mymoscow",
    tag_count: 5,
  },
  {
    id: 3,
    imageURL: "projects/ladoga/logo.png",
    name: "projects/ladogaGuide",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 4,
    imageURL: "projects/guidekur/logo.png",
    name: "projects/kurortnyyGuide",
    content_locales: "guidekur",
    tag_count: 1,
  },
  {
    id: 5,
    imageURL: "projects/brodilkamoscow/logo.png",
    name: "projects/questMoscow",
    content_locales: "brodilkamoscow",
    tag_count: 1,
  },
  {
    id: 6,
    imageURL: "projects/publicart/logo.png",
    name: "projects/publicart",
    content_locales: "publicart",
    tag_count: 4,
  },
  {
    id: 7,
    imageURL: "projects/myviborg/logo.png",
    name: "projects/myViborg",
    content_locales: "myviborg",
    tag_count: 2,
  },
  {
    id: 8,
    imageURL: "projects/geniusloci/logo.png",
    name: "projects/geniusLociMemo",
    content_locales: "geniusloci",
    tag_count: 2,
  },
  {
    id: 9,
    imageURL: "projects/brodilkakurortnyy/logo.png",
    name: "projects/questKurortnyy",
    content_locales: "brodilkakurortnyy",
    tag_count: 1,
  },
  {
    id: 10,
    imageURL: "projects/streetart/logo.png",
    name: "projects/streetArtMemo",
    content_locales: "streetart",
    tag_count: 1,
  },
];

export const nftList: Project[] = [
  {
    id: 0,
    imageURL: "nft/interior/logo.png",
    name: "nft/nftInterior",
    content_locales: "nft_list.interior",
    tag_count: 1,
  },
  {
    id: 1,
    imageURL: "nft/newcityartist/logo.png",
    name: "nft/newCityDriver",
    content_locales: "nft_list.newcity",
    tag_count: 1,
  },
  {
    id: 2,
    imageURL: "nft/btrNft/logo.png",
    name: "nft/backToTheRoots",
    content_locales: "nft_list.btrNft",
    tag_count: 1,
  },
  {
    id: 3,
    imageURL: "nft/dirtydrops/logo.png",
    name: "nft/dirtydrops",
    content_locales: "nft_list.dirtydrops",
    tag_count: 1,
  },
  {
    id: 4,
    imageURL: "nft/newnames/logo.png",
    name: "nft/newNamesInFashion",
    content_locales: "nft_list.newnames",
    tag_count: 1,
  },
  {
    id: 5,
    imageURL: "nft/metafemhistory/logo.png",
    name: "nft/metafemhistory",
    content_locales: "nft_list.metafemhistory",
    tag_count: 1,
  },
  {
    id: 6,
    imageURL: "nft/neweast/logo.png",
    name: "nft/newEastTechAwards",
    content_locales: "nft_list.neweast",
    tag_count: 1,
  },
  {
    id: 7,
    imageURL: "nft/halloween/logo.png",
    name: "nft/halloween",
    content_locales: "nft_list.halloween",
    tag_count: 1,
  },
];
