import { useTranslation } from "react-i18next";
import { Project } from "../../types/types";

export const projectsList: Project[] = [
  {
    id: 0,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 1,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 2,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 3,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 4,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 5,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 6,
    imageURL: "projects/ladoga/logo.png",
    name: "ladogaGuide",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 7,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 8,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 9,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 10,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 11,
    imageURL: "projects/publicart/logo.png",
    name: "myMoscow",
    content_locales: "ladoga",
    tag_count: 1,
  },
  // {
  //   id: 12,
  //   imageURL: "projects/publicart/logo.png",
  // name: "myMoscow",
  // content_locales: "ladoga",
  // tag_count: 1,
  // },
];
