import { Project } from "types/types";

export const projectsList: Project[] = [
  {
    id: 0,
    imageURL: "projects/brodilkaviborg/logo.png",
    name: "projects/questViborg",
    content_locales: "brodilkaviborg",
    tag_count: 1,
  },
  {
    id: 1,
    imageURL: "projects/backtotheroots/logo.png",
    name: "projects/backToTheRootsLanding",
    content_locales: "backtotheroots",
    tag_count: 1,
  },
  {
    id: 2,
    imageURL: "projects/mymoscow/logo.png",
    name: "projects/myMoscow",
    content_locales: "mymoscow",
    tag_count: 5,
  },
  {
    id: 3,
    imageURL: "projects/ladoga/logo.png",
    name: "projects/ladogaGuide",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 4,
    imageURL: "projects/guidekur/logo.png",
    name: "projects/kurortnyyGuide",
    content_locales: "guidekur",
    tag_count: 1,
  },
  {
    id: 5,
    imageURL: "projects/brodilkamoscow/logo.png",
    name: "projects/questMoscow",
    content_locales: "brodilkamoscow",
    tag_count: 1,
  },
  {
    id: 6,
    imageURL: "projects/publicart/logo.png",
    name: "projects/publicart",
    content_locales: "publicart",
    tag_count: 4,
  },
  {
    id: 7,
    imageURL: "projects/myviborg/logo.png",
    name: "projects/myViborg",
    content_locales: "myviborg",
    tag_count: 2,
  },
  {
    id: 8,
    imageURL: "projects/geniusloci/logo.png",
    name: "projects/geniusLociMemo",
    content_locales: "geniusloci",
    tag_count: 2,
  },
  {
    id: 9,
    imageURL: "projects/brodilkakurortnyy/logo.png",
    name: "projects/questKurortnyy",
    content_locales: "brodilkakurortnyy",
    tag_count: 1,
  },
  {
    id: 10,
    imageURL: "projects/streetart/logo.png",
    name: "projects/streetArtMemo",
    content_locales: "streetart",
    tag_count: 1,
  },
];
