import { useTranslation } from "react-i18next";
import { Project } from "../../types/types";

export const projectsList: Project[] = [
  {
    id: 0,
    imageURL: "projects/brodilkaviborg/logo.png",
    name: "myMoscow",
    content_locales: "brodilkaviborg",
    tag_count: 1,
  },
  {
    id: 1,
    imageURL: "projects/backtotheroots/logo.png",
    name: "backToTheRootsLanding",
    content_locales: "backtotheroots",
    tag_count: 1,
  },
  {
    id: 2,
    imageURL: "projects/mymoscow/logo.png",
    name: "myMoscow",
    content_locales: "mymoscow",
    tag_count: 5,
  },
  {
    id: 3,
    imageURL: "projects/publicart/logo.png",
    name: "publicart",
    content_locales: "publicart",
    tag_count: 4,
  },
  {
    id: 4,
    imageURL: "projects/brodilkamoscow/logo.png",
    name: "publicart",
    content_locales: "brodilkamoscow",
    tag_count: 1,
  },
  {
    id: 5,
    imageURL: "projects/putevoditel/logo.png",
    name: "myMoscow",
    content_locales: "putevoditel",
    tag_count: 1,
  },
  {
    id: 6,
    imageURL: "projects/ladoga/logo.png",
    name: "ladogaGuide",
    content_locales: "ladoga",
    tag_count: 1,
  },
  {
    id: 7,
    imageURL: "projects/myviborg/logo.png",
    name: "myViborg",
    content_locales: "myviborg",
    tag_count: 2,
  },
  {
    id: 8,
    imageURL: "projects/geniusloci/logo.png",
    name: "geniusLociMemo",
    content_locales: "geniusloci",
    tag_count: 1,
  },
  {
    id: 9,
    imageURL: "projects/streetart/logo.png",
    name: "streetArtMemo",
    content_locales: "streetart",
    tag_count: 1,
  },
  {
    id: 10,
    imageURL: "projects/brodilkakurortniy/logo.png",
    name: "myMoscow",
    content_locales: "brodilkakurortniy",
    tag_count: 1,
  },
  // {
  //   id: 11,
  //   imageURL: "projects/publicart/logo.png",
  //   name: "myMoscow",
  //   content_locales: "ladoga",
  //   tag_count: 1,
  // },
  // {
  //   id: 12,
  //   imageURL: "projects/publicart/logo.png",
  // name: "myMoscow",
  // content_locales: "ladoga",
  // tag_count: 1,
  // },
];
